
[build]
  publish = "public"
  command = "npm run build"

[[redirects]]
  from = "/old-page"
  to = "/new-page"
  status = 301
  force = true

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200
